Repository ISTE-500-501-TeamWatchHill/frontend, pull requests merged in 2023-02, with the labels that each got.

#8 Finishing Navbar
  src/App.js
  src/components/button/button.css
  src/components/navbar/navbar.css
  src/components/navbar/navbar.js
  src/components/navlink/navlink.css
  src/components/navlink/navlink.js
Labels: Needs Review

#11 Homepage
  package-lock.json
  package.json
  src/App.js
  src/components/button/button.js
  src/components/navbar/navbar.css
  src/components/navbar/navbar.js
  src/components/navlink/navlink.js
  src/components/spacer/spacer.js
  src/pages/home/home.css
  src/pages/home/home.js
Labels: Needs Review

#10 Branch for team and universities page
  package-lock.json
  package.json
  src/App.js
  src/components/placeholder.png
  src/components/searchbar/searchbar.css
  src/components/searchbar/searchbar.js
  src/components/teamblock/teamblock.css
  src/components/teamblock/teamblock.js
  src/pages/teamsanduniversities/team/team.css
  src/pages/teamsanduniversities/team/team.js
  src/pages/teamsanduniversities/teamsanduniversities.js
  src/pages/teamsanduniversities/teamsanduniversities/teamsanduniversities.css
  src/pages/teamsanduniversities/teamsanduniversities/teamsanduniversities.js
Labels: Ready to Merge

#12 im trying my best pls dont judge
  src/pages/aardvarkgames/aardvarkgames/aardvarkgames.css
  src/pages/aardvarkgames/aardvarkgames/aardvarkgames.js
Labels: Work in Progress

#13 Fixed compile issues, homepage issue, and added font
  README.md
  package-lock.json
  package.json
  src/components/teamblock/teamblock.js
  src/pages/aardvarkgames/aardvarkgames/aardvarkgames.css
  src/pages/aardvarkgames/aardvarkgames/aardvarkgames.js
  src/pages/home/home.css
  src/pages/home/home.js
  src/pages/teamsanduniversities/team/team.js
  src/pages/teamsanduniversities/teamsanduniversities/teamsanduniversities.js
Labels: Needs Review

#15 Tournament Page beginnings
  src/pages/aardvarkgames/aardvarkgames/aardvarkgames.css
  src/pages/aardvarkgames/aardvarkgames/aardvarkgames.js
  src/pages/home/home.css
  src/pages/home/home.js
  src/pages/teamsanduniversities/teamsanduniversities/teamsanduniversities.js
  src/pages/tournament/tournament/tournament.css
  src/pages/tournament/tournament/tournament.js
Labels: Needs Review

#16 Footer
  src/App.js
  src/components/Aardvark_logo_clear.png
  src/components/footer/footer.css
  src/components/footer/footer.js
  src/pages/home/home.js
Labels: Needs Review

#18 Button Props
  src/components/button/button.css
  src/components/button/button.js
  src/components/button/button.module.css
  src/pages/home/home.js
Labels: Needs Review

#19 Cypress
  cypress.config.js
  cypress/e2e/navigation.spec.cy.js
  cypress/fixtures/example.json
  cypress/support/commands.js
  cypress/support/e2e.js
  package.json
  src/components/navbar/navbar.js
  src/components/navlink/navlink.js
  yarn.lock
Labels: Needs Review

#17 Teams and University Pages
  src/App.js
  src/components/memberblock/memberblock.css
  src/components/memberblock/memberblock.js
  src/components/teamblock/teamblock.js
  src/pages/teamsanduniversities/team/team.js
  src/pages/teamsanduniversities/teamsanduniversities/teamsanduniversities.js
  src/pages/teamsanduniversities/university/university.css
  src/pages/teamsanduniversities/university/university.js
Labels: Needs Review

#22 Adding static content, updating footer, and more
  new_component.sh
  public/index.html
  src/components/button/button.js
  src/components/footer/footer.js
  src/components/footer/footer.module.css
  src/components/searchbar/searchbar.js
  src/components/searchbar/searchbar.module.css
  src/pages/aardvarkgames/aardvarkgames/aardvarkgames.js
  src/pages/aardvarkgames/boardgame/boardgame.css
  src/pages/aardvarkgames/boardgame/boardgame.js
  src/pages/aardvarkgames/boardgame/boardgame.module.css
  src/pages/home/home.js
  src/pages/home/home.module.css
  src/pages/login/login.js
  src/pages/login/login.module.css
  src/pages/pages.module.css
  src/pages/registration/registration.js
  src/pages/registration/registration.module.css
  src/pages/tournament/tournament/tournament.js
  src/pages/tournament/tournament/tournament.module.css
Labels: Needs Review

#25 Multilingual capabilities
  package.json
  src/assets/translations/en.json
  src/assets/translations/es.json
  src/components/footer/footer.js
  src/components/languageselector/languageselector.js
  src/components/languageselector/languageselector.module.css
  src/components/navbar/navbar.js
  src/i18n.js
  src/index.js
  src/pages/home/home.js
  yarn.lock
Labels: Needs Review

#26 Registration and login requests store token
  package-lock.json
  src/pages/login/login.js
  src/pages/registration/registration.js
  yarn.lock
Labels: Needs Review

#28 WH-104: Login & Logout functionality
  .env.example
  new_component 2.sh
  package-lock.json
  package.json
  src/App.js
  src/components/button/button.js
  src/components/footer/footer.js
  src/components/languageselector/languageselector.js
  src/components/navbar/navbar.js
  src/components/searchbar/searchbar.module 2.css
  src/components/teamblock/teamblock.js
  src/pages/aardvarkgames/aardvarkgames/aardvarkgames.js
  src/pages/aardvarkgames/boardgame/boardgame.js
  src/pages/adminmoderatorlogin/adminmoderatorlogin.js
  src/pages/adminmoderatorlogin/adminmoderatorlogin.module.css
  src/pages/login/login.js
  src/pages/registration/registration.js
  src/pages/teamsanduniversities/university/university.js
  yarn.lock
Labels: Work in Progress
