Repository ISTE-500-501-TeamWatchHill/frontend, pull requests merged in 2023-03, with the labels that each got.

#29 Countdown timer
  src/components/countdowntimer/countdowntimer.js
  src/components/countdowntimer/countdowntimer.module.css
  src/pages/home/home.js
  src/pages/home/home.module.css
Labels: Needs Review

#30 WH-108: Attach backend & finish t&u page
  package-lock.json
  src/App.js
  src/components/teamblock/teamblock.js
  src/methods.js
  src/pages/login/login.js
  src/pages/teamsanduniversities/teamsanduniversities/teamsanduniversities.js
Labels: Work in Progress

#32 Schedule page creation and layout to prep for games data endpoint
  src/components/gameblock/gameblock.js
  src/components/gameblock/gameblock.module.css
  src/pages/tournament/schedule/schedule.js
Labels: Ready to Merge

#35 WH-111: Csshighfidelity
  src/assets/images/firstPrize.png
  src/assets/images/homeBackground.png
  src/assets/images/universities/cornell_circle.png
  src/assets/images/universities/delhi_circle.png
  src/assets/images/universities/dublin_circle.png
  src/assets/images/universities/kyoto_circle.png
  src/assets/images/universities/pontificia_circle.png
  src/assets/images/universities/rit_circle.png
  src/assets/translations/en.json
  src/assets/translations/es.json
  src/components/button/button.js
  src/components/button/button.module.css
  src/components/countdowntimer/countdowntimer.module.css
  src/components/footer/footer.module.css
  src/pages/aardvarkgames/aardvarkgames/aardvarkgames.js
  src/pages/aardvarkgames/boardgame/boardgame.js
  src/pages/home/home.js
  src/pages/home/home.module.css
  src/pages/pages.module.css
  src/pages/teamsanduniversities/team/team.js
  src/pages/teamsanduniversities/teamsanduniversities/teamsanduniversities.js
  src/pages/teamsanduniversities/university/university.js
  src/pages/tournament/schedule/schedule.js
  src/pages/tournament/tournament/tournament.js
Labels: Needs Review

#36 Csshighfidelity
  src/assets/images/boardGameBackground.png
  src/assets/images/homeNavBackground.png
  src/components/navbar/navbar.js
  src/components/navbar/navbar.module.css
  src/components/navlink/navlink.module.css
  src/pages/aardvarkgames/aardvarkgames/aardvarkgames.js
  src/pages/aardvarkgames/boardgame/boardgame.js
  src/pages/aardvarkgames/boardgame/boardgame.module.css
  src/pages/home/home.js
  src/pages/pages.module.css
Labels: Ready to Merge

#33 Added more instructions to frontend README
  README.md
  new_component 2.sh
Labels: Needs Review

#45 Hificss
  src/assets/images/aardvarkAboutBackground.png
  src/assets/images/boardGameBackground.png
  src/assets/images/boardGameImages.png
  src/assets/images/loginsidepanel.png
  src/assets/images/registersidepanel.png
  src/assets/images/tournamentAboutBackground.png
  src/assets/images/tournamentAboutBottom.png
  src/components/countdowntimer/countdowntimer.module.css
  src/components/navbar/navbar.js
  src/pages/aardvarkgames/aardvarkgames/aardvarkgames.js
  src/pages/aardvarkgames/aardvarkgames/aardvarkgames.module.css
  src/pages/aardvarkgames/boardgame/boardgame.js
  src/pages/aardvarkgames/boardgame/boardgame.module.css
  src/pages/home/home.js
  src/pages/home/home.module.css
  src/pages/login/login.js
  src/pages/login/login.module.css
  src/pages/pages.module.css
  src/pages/registration/registration.js
  src/pages/registration/registration.module.css
  src/pages/tournament/tournament/tournament.js
  src/pages/tournament/tournament/tournament.module.css
Labels: Needs Review

#44 WH-38: Adding all games endpoint
  src/components/gameblock/gameblock.js
  src/pages/tournament/schedule/schedule.js
Labels: Needs Review

#42 WH-133: Adding Profile Page
  public/profile.png
  src/App.js
  src/assets/images/profile.png
  src/components/navbar/navbar.js
  src/components/navbar/navbar.module.css
  src/pages/profile/profile.js
  src/pages/profile/profile.module.css
Labels: Work in Progress

#40 WH-114: Creating teams
  package-lock.json
  src/App.js
  src/components/button/button.js
  src/components/button/button.module.css
  src/components/navbar/navbar.js
  src/pages/aardvarkgames/aardvarkgames/aardvarkgames.js
  src/pages/teamsanduniversities/create-team/create-team.js
  src/pages/teamsanduniversities/create-team/create-team.module.css
  src/pages/teamsanduniversities/team/team.js
  src/pages/teamsanduniversities/team/team.module.css
  src/pages/teamsanduniversities/teamsanduniversities/teamsanduniversities.module.css
  yarn.lock
Labels: Work in Progress
